captainVersion: 4
services:
    $$cap_appname:
        image: satont/yakui
        restart: always
        environment:
            DB_HOST: $$cap_yakui_db_host
            DB_PORT: 5432
            DB_USER: yakui
            DB_PASSWORD: yakui
            ADMINER_DESIGN: $$cap_adminer_design
        caproverExtra:
            containerHttpPort: '3000'
caproverOneClickApp:
    variables:
        - id: $$cap_yakui_db_host
          label: 'OPTIONAL: DB HOST'
          defaultValue: 'srv-captain--yakui-db'
          validRegex: /^([a-zA-Z0-9-.\s])*$/
    instructions:
        start: >-
            Yakui
        end: Yakui is deployed as $$capappname
    displayName: Yakui
    isOfficial: false
    description: Yakui
    documentation: ''